yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # Main page
    path('', views.index, name='index'),
    # Any another page
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # User proflie
    path('profile/<str:username>/', views.profile, name='profile'),
    # Posts view
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Create post
    path('create/', views.post_create, name='post_create'),
    # Post edit
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Delite post
    path(
        'delete/<int:post_id>',
        views.delete_post,
        name='delete_post'
    ),
    # Add comment
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    # Follow
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth import get_user_model

# Автоматически создаем таблицу для пользователя
User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text='Укажите название группы'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Уникальный адрес группы',
        help_text='Выберите из списка или укажите новый адрес'
    )
    description = models.TextField(
        verbose_name='Описание сообщества',
        help_text='Добавьте описание группы'
    )

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Добавьте описание поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата публикации поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
        help_text='Выберите автора поста'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Укажите группу, в которой опубликуется пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ("-pub_date",)
        verbose_name = "Пост"

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария',
        blank=True
    )
    created = models.DateTimeField(
        'Дата публикации комментария',
        auto_now_add=True,
        db_index=True
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )

class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_follows')
        ]

yatube/posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = {'text': 'Текст', 'group': 'Группа', 'image': 'Картинка'}
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост'
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Comment, Follow
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from .utils import paginate_page

def index(request):
    posts = Post.objects.select_related('group', 'author')
    page_obj = paginate_page(request, posts)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related("author", "group")
    page_obj = paginate_page(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group', 'author')
    page_obj = paginate_page(request, posts)
    if request.user.is_authenticated:
        following = request.user.follower.filter(author=author).exists()
    else:
        following = False
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post=post)
    context = {
        'author': author,
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST, files=request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
    context = {
        'is_edit': False,
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)
    context = {
        'is_edit': True,
        'form': form,
        'post_id': post_id
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.user == post.author:
        post.delete()
    return redirect('posts:index')


# КОММЕНТАРИИ


@login_required
def add_comment(request, post_id):
    """Создание комментария."""
    post = Post.objects.get(id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


# ПОДПИСКА-ОТПИСКА


@login_required
def follow_index(request):
    # информация о текущем пользователе доступна в переменной request.user
    title = "Страница постов с подписками"
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = paginate_page(request, posts)
    context = {
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)

@login_required
def profile_follow(request, username):
    """Функция подписки на автора."""
    author = get_object_or_404(User, username=username)
    check_follow = Follow.objects.filter(
        author=author, user=request.user
    ).exists()
    if not check_follow and request.user != author:
        request.user.follower.create(author=author)
    return redirect('posts:follow_index')

@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = get_object_or_404(
        Follow,
        author=author.id,
        user=request.user.id
    )
    follow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}{% endblock %}
{% block content %}
{% load user_filters %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}</div>
              <div class="card-body">        
                <form method="post"
                  {% if is_edit %}
                  <form method="post" enctype="multipart/form-data"
                    action="{% url 'posts:post_edit' post_id %}"
                  {% else %}
                  <form method="post" enctype="multipart/form-data"
                    action="{% url 'posts:post_create' %}"
                  {% endif %}
                >
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.text }}              
                    <small id="id_text-help" class="form-text text-muted">
                      {% if is_edit %}
                      Отредактированная запись
                      {% else %}
                      Текст новой записи
                      {% endif %}    
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    {{ form.group }}
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка                  
                    </label>
                    {{ form.image }}
                    <small id="id_image-help" class="form-text text-muted">
                      Выберите картинку для поста
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                      Сохранить
                      {% else %}
                      Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
  <br>
    {% include 'posts/includes/post_list.html' %}
    <p>{{ post.text|truncatechars:300 }} </p>
      <a class="btn btn-primary" href="{% url 'posts:post_detail' post.id %}">
        Подробная информация о посте
      </a>
    <br>
    <br>
    {% if post.group %}
    <b>Все записи группы: </b>
    <a class="btn btn-primary" href="{% url 'posts:group_list' post.group.slug %}">{{ post.group }}</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} {{ group.slug }} {% endblock %}
{% block content %}
<div class="container py-5">    
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
  {% include 'posts/includes/post_list.html' %}
{% include 'posts/includes/thumbnail.html' %}
<p> {{ post.text }} </p>
{% if post.group %}
<a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% include 'posts/includes/paginator.html' %} 
</div>  
{% endblock content%}

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<head>
{% extends 'base.html' %}
{% load cache %}
{% block title %} {{ title }} {% endblock %}
</head>
  {% block header %} {% include 'includes/header.html' %} {% endblock header %}
{% block content %}
{% cache 20 index_page page_obj.number %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">
  <h1>{{ title }}</h1>
  {% for post in page_obj %}
  {% include 'posts/includes/post_list.html' %}
    {% include 'posts/includes/thumbnail.html' %}
    <p> {{ post.text }} </p>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'posts/includes/paginator.html' %}
  <!-- под последним постом нет линии -->
</div>  
{% endcache %} 
{% endblock content%}
{% block footer %} {% include 'includes/footer.html' %} {% endblock footer %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{ post.text|truncatechars:30 }} {% endblock %}
{% block content %}
<div class="container py-5">        
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>

            {% if post.group %}   
            <li class="list-group-item">
              Группа: {{ post.group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{ post.author.posts.count }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% include 'posts/includes/thumbnail.html' %}
          <p>{{ post.text|linebreaksbr }} </p>
          {% if user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>
          <a class="btn btn-primary" href="{% url 'posts:delete_post' post.id %}">
            удалить запись
          </a>
          {% endif %}
    </div> 
    {% load user_filters %}
    
    {% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 
  </main>
</body>
</html> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {%include 'posts/includes/following.html' %}
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% include 'posts/includes/thumbnail.html' %}
          </ul>
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>
        {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}    
      </div>
{% endblock %}